sudo: false
language: java
jdk:
- oraclejdk7
notifications:
  email:
    recipients:
    - betfair-cougar-dev@googlegroups.com
    on_success: always
    on_failure: always
before_install:
- gem install --version 0.8.9 faraday
- gem install travis-artifacts
- echo 'MAVEN_OPTS = $MAVEN_OPTS'
install: echo 'No install command here!'
script: bash buildArchetypes.sh
after_success:
- bash deploySnapshots.sh
env:
  global:
  - secure: SpkGmmIzhna67TtKQt9dgeO+wlXNHYVXuLjNz0p/mfTL97fea+lgSfAYII9l9VC2qdGQ/NDOqE9waYFMXcI+pNqYxDBKPoV7OAsOalLUQLa8i9jj9u1jMtTqgCySakKuuh1P1kmFEAQ0LNcnkH//QUG/9R5dLy+p/NWHiZFBJAE=
  - secure: DQGaCoJGjAgZWgAu+x+Bgea++yFrEnt7xU5+7ExVHWIsA+yY+hS19fEAxRPJiPDgP/EnCvvP0QjWQIEBWMrVDy3xBFszHJnyJIDycFu+LfnAuvAopc4I9Lue8vb1xxlYLZpZ8MOhJ+fKRoToD80ifOhhgNKdk/otOn7D3fR6LYQ=
